team_names = [
    'The Perfecto’s', 'Shooting Stars', 'Basket Junkies', 'The Hot Shots',
    'The Crush', 'Jayhawks', 'Savage Storm', 'Basket Hounds',
    'Panthers', 'Shockers', 'Net Rippers', 'The Crusaders',
    'Defenders', 'The Heat', 'Matadors', 'Saxons'
]

fname_lname_pairs = [
    ['Billy', 'Cresswell'], ['Antone', 'Amrhein'], ['Hans', 'Stejskal'], ['Morgan', 'Brownson'],
    ['Guy', 'Sylvestre'], ['Weston', 'Erion'], ['Dirk', 'Holiday'], ['Carroll', 'Crary'],
    ['Will', 'Sugrue'], ['Yong', 'Hanchett'], ['Alonzo', 'Berwick'], ['Tyson', 'Thong'],
    ['Nicky', 'Steinman'], ['Lynwood', 'Neault'], ['Jeromy', 'Ota'], ['Tuan', 'Faber'],
    ['Javier', 'Imes'], ['Thad', 'Cloyd'], ['Dwayne', 'Sawtelle'], ['Delmar', 'Vanfleet'],
    ['Kraig', 'Leff'], ['Chance', 'Waller'], ['Jared', 'Creasman'], ['Leif', 'Dolan'],
    ['Leandro', 'Goering'], ['Everette', 'France'], ['Filiberto', 'Comeau'], ['Newton', 'Balas'],
    ['Bert', 'Moline'], ['Burton', 'Liss'], ['Bart', 'Danos'], ['Mohamed', 'Cubbage'],
    ['Reggie', 'Brugnoli'], ['Kenny', 'Badon'], ['Collin', 'Slade'], ['Quinton', 'Dowless'],
    ['Jules', 'Abbe'], ['Nathan', 'Plowden'], ['Mickey', 'Ledonne'], ['Harley', 'Worthley'],
    ['Harrison', 'Tomczak'], ['Ervin', 'Dryden'], ['Oren', 'Tavares'], ['Anthony', 'Hardegree'],
    ['Terence', 'Moctezuma'], ['Herman', 'Grimmett'], ['Carlo', 'Bertolino'],
    ['Rodrick', 'Waldrop'],
    ['Jay', 'Franceschi'], ['Ariel', 'Queener'], ['Courtney', 'Kenny'], ['Todd', 'Gourley'],
    ['Mack', 'Kane'], ['Everett', 'Mallard'], ['Corey', 'Flamm'], ['William', 'Hornbaker'],
    ['Jerry', 'Meunier'], ['Royce', 'Sweatman'], ['Phil', 'Brawn'], ['Fredric', 'Auxier'],
    ['Hilton', 'Pharr'], ['Jordon', 'Pasek'], ['Abram', 'Lees'], ['Lucien', 'Philips'],
    ['Keven', 'Deangelis'], ['Lino', 'Lashua'], ['Thurman', 'Stradley'], ['Loyd', 'Lamberton'],
    ['Antone', 'Meshell'], ['Fermin', 'Vicente'], ['Federico', 'Besaw'], ['Dewey', 'Miyashiro'],
    ['Shon', 'Stancil'], ['Floyd', 'Brunn'], ['Devon', 'Tullos'], ['Nicholas', 'Arana'],
    ['Edmund', 'Starr'], ['Melvin', 'Salmeron'], ['Bradly', 'Spurlin'], ['Augustus', 'Robledo'],
    ['Earl', 'Hampton'], ['Alonzo', 'Alpers'], ['Kenny', 'Kriner'], ['Trey', 'Forbush'],
    ['Guillermo', 'Casler'], ['Russel', 'Lessman'], ['Philip', 'Caviness'], ['Alva', 'Beecroft'],
    ['Vance', 'Kestner'], ['Freeman', 'Santiago'], ['Bertram', 'Hough'], ['Carmen', 'Hedstrom'],
    ['Donny', 'Ruffino'], ['Santos', 'Baze'], ['Raymond', 'Sabado'], ['Eddie', 'Guertin'],
    ['Lee', 'Rascon'], ['Ralph', 'Luebbert'], ['Dwayne', 'Caspers'], ['Adolph', 'Harper'],
    ['Daron', 'Lindblom'], ['Cristobal', 'Vanfleet'], ['Parker', 'Dirksen'], ['Dale', 'Furby'],
    ['Lonnie', 'Swigart'], ['Rickie', 'Puzo'], ['Reynaldo', 'Rakestraw'], ['Clyde', 'Collar'],
    ['Hal', 'Raynes'], ['Edwardo', 'Cresswell'], ['Titus', 'Steller'], ['Nolan', 'Heims'],
    ['Gale', 'Walmsley'], ['Alphonso', 'Porcaro'], ['Eusebio', 'Frances'], ['Wilford', 'Lewallen'],
    ['Dexter', 'Heckathorn'], ['Elijah', 'Stgermain'], ['Mitchell', 'Halley'], ['Odis', 'Burgess'],
    ['Nelson', 'Prendergast'], ['Chuck', 'Garabedian'], ['Brett', 'Bockman'], ['Buster', 'Hiney'],
    ['Norbert', 'Moodie'], ['Toby', 'Burges'], ['Tristan', 'Soper'], ['Amado', 'Enfinger'],
    ['Rodrick', 'Whittingham'], ['Donovan', 'Murrieta'], ['Jacinto', 'Pavia'], ['Tyson', 'Burpee'],
    ['Hans', 'Tran'], ['Ahmed', 'Jeon'], ['Kim', 'Channel'], ['Ira', 'Stroh'],
    ['Clifton', 'Quinley'],
    ['Charles', 'Shouse'], ['Benito', 'Payson'], ['Connie', 'Brinson'], ['Jamey', 'Difiore'],
    ['Trinidad', 'Phinney'], ['Merlin', 'Farrier'], ['Jesse', 'Stevens'], ['Lacy', 'Whorton'],
    ['Woodrow', 'Izaguirre'], ['Wes', 'Fried'], ['Delmar', 'Munsterman'],
    ['Christopher', 'Godfrey'],
    ['Timmy', 'Schaaf'], ['Dong', 'Tutt'], ['Gregorio', 'Hornback'], ['Elmer', 'Feeley'],
    ['Emory', 'Zeck'], ['Cletus', 'Mclain'], ['Lamar', 'Cummingham'], ['Elden', 'Pariseau'],
    ['Ward', 'Pinero'], ['David', 'Scholl'], ['Merle', 'Weesner'], ['Guadalupe', 'Peltz'],
    ['Toby', 'Balicki'], ['Ned', 'Panek'], ['Aron', 'Boulton'], ['Zachery', 'Robuck'],
    ['Salvador', 'Tuohy'], ['Chas', 'Knights'], ['Theodore', 'Gurney'], ['Whitney', 'Viator'],
    ['Noble', 'Ta'], ['Rocky', 'Beadle'], ['Cleveland', 'Bermudes'], ['Sebastian', 'Kindle'],
    ['Benedict', 'Kapinos'], ['Quinn', 'Storck'], ['Israel', 'Milby'], ['Giuseppe', 'Maley'],
    ['Monty', 'Billington'], ['Marcellus', 'Sage'], ['Garrett', 'Arpin'], ['Hassan', 'Alvelo'],
    ['Andreas', 'Ashlock'], ['Ralph', 'Toups'], ['Aubrey', 'Styers'], ['Grant', 'Crisci'],
    ['Kasey', 'Shroyer'], ['Cruz', 'Cosme'], ['Lenard', 'Stampley'], ['Erasmo', 'Organ'],
    ['Nickolas', 'Newlon'], ['Burton', 'Sam'], ['Modesto', 'Birkholz'], ['Clemente', 'Garry'],
    ['Alan', 'Meiser'], ['Florentino', 'Brasil'], ['Franklin', 'Harlow'], ['Edmund', 'Fryman'],
    ['Rodney', 'Gonce'], ['Steve', 'Mcdonnell'], ['Ernie', 'Lomonaco'],
]

